### ISSUE TITLE
Mining fees too high, transaction information confusing?

### ISSUE THREAD

**Issue by cryptoeraser** [wavesplatform/WavesWallet-iOS#252]
Hi,

We are testing the Waves wallet right now. We have made a Bitcoin transaction out of one of our Waves wallet to a Copay Bitcoin wallet. For the transaction we have paid 0.001 WAVES in network fees. However, we have also incurred 0.001 BTC in mining fees, which seems too high.

We have sent 0.005811 BTC out of our Waves wallet and received 0.004811 on the other side.

![transaction](https://user-images.githubusercontent.com/36895777/53089579-e040df80-3504-11e9-92f8-50e6fa95e3db.png)

This seems to be the transaction ID which does not make a lot of sense:
[1afb6a49158492f2af5ca0a8abd04d242997b35db8f8132bdf5809380d1dc9e3](https://www.blockchain.com/btc/tx/1afb6a49158492f2af5ca0a8abd04d242997b35db8f8132bdf5809380d1dc9e3)

Could you please help me understand what might have happened here?

Thanks,

**Comment by cryptoeraser** [comment]
And this is the transaction ID on the waves network.
[9acB2duLnSs8GnMo7frJJFu2c1eE5HuTxajba9A4U4F1](https://wavesexplorer.com/tx/9acB2duLnSs8GnMo7frJJFu2c1eE5HuTxajba9A4U4F1)

**Comment by cryptoeraser** [comment]
It seems like this is the answer:

[payment-gatewayl](https://docs.wavesplatform.com/en/waves-client/frequently-asked-questions-faq/transfers-and-gateways/payment-gateway.html)

**Comment by mefilt** [comment]
Good job!
